### PR TITLE
New data correction types

### PR DESCRIPTION
**Pull request by Sidane**
## Feature change

Add new data correction types for:

* company registration
* trading name
* trading date
* generic fields 1 - 5

## Refactor

Also includes a pretty hefty refactor of data corrections. This was to avoid having to add more and more new columns to the `loan_modifications` table every time we add a new data correction type (16 columns in this case).

Includes:

* Moving `DataCorrection` into its own table.

* Storing all data correction changes (old and new values) in a serialized column. For reversibility all old data correction columns have been moved from the `loan_modifications` table to the `data_corrections` table, prefixed with `_legacy_<column_name>`.

* Moving the data correction data out of `loan_modifications`. We identified all records that had a mix of loan changes and data corrections (a carry over from how the legacy system worked). For these records, we kept the loan change record and created a new data correction record with the relevant data. Data correction fields on `loan_modifications` are now removed.

* Validating data corrections are changing the data. Previously you could create a new data correction record which changed nothing. As part of this, we deleted any records that have no data correction changes.

* DRYing up the basic single field data corrections into a reusable `BasicDataCorrectable` module.

* DRYing up basic data corrections spec into shared examples.

* DRYing up setting of `seq` on various models (includes standardising default value of seq to 0, it was 1 on some models).

* Changing `loan_modifications` resource to `loan_amendments` to better encapsulate the concept of loan_modifications and data_corrections. It also has its own `LoanAmendmentPresenter` now.

* Adding a new sortcode `ChangeType` with a data migration to update any data corrections that should have that type. Previously they had a change type of 'Data correction'.

### CODE REVIEW

**Comment by jabley** [comment]
:+1:  Nice work.

I'm having problems getting `master` to build in our CI environment (it was
due to be destroyed 2 years ago, so is a unique snowflake). I'll hold off
merging this if that's OK, until I can get `master` happy.

**Comment by Sidane** [comment]
Yep, that's fine.

**Comment by Sidane** [comment]
Ben has reviewed this and is going to make a few tweaks, so we'll let you know when it's ready to merge.

**Comment by Sidane** [comment]
:+1:

**Comment by benpickles** [comment]
Done.

https://github.com/alphagov/EFG/compare/9fe34c1...e15c41f

This is ready to merge.

**Comment by benpickles** [comment]
Actually, please wait to merge, I have found a little bug.

**Comment by benpickles** [comment]
Ready to merge again.

**Pull request merged**
